### ISSUE TITLE
Write configuration to default data location of Egeria

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-crux#14]
The simplest way to passthrough the configuration is to serialise it to JSON, and then pass this through to Crux as its configuration file -- but this requires writing the information out to a file somewhere for Crux's API to consume.

Currently we're doing this via Java's built-in temporary file mechanism (`File.createTempFile`), which while platform-agnostic does not put the file in the most obvious location...  It would be nice to leverage Egeria's own data locations (ie. `data/servers/...`) instead.

@planetf1 is this data location exposed via any Egeria helpers, perhaps?

**Comment by planetf1** [comment]
I saw the reference in your config issue. It's a good question. As you say by default we now use <distroot>/data for config, registrystore etc, the intent being to make it easy in a docker/k8s environment to have a volume mounted at that location to allow for persistence.

Indeed by having a somewhat logical structure along the platform/server basis at the top level, the hope was that if further volumes were required it was clearer where they could be mounted, it just for the graph store for one specific server 

The location is currently hardcoded as relative to the current working directory -- so if that is changed prior to starting, that will affect the data file location. In our standard docker image we run 'server/xxx.jar' so we have data at the top level alongside server (from the distribution). In a dev environment most will probably have it directly under the source root.

The value is only used as a default, so through the rest api other locations can be used. 

Making the default available, especially for reading, via an API, would seem to be useful. They could assume './data' just like other code but a) that is more error prone and b) less easy to change. Of course that might then beg the question of how fine grained to get. As well as the base directory for data should we return platform specific? or server specific directories? Or connector specific?

In many environments it's quite possible we don't want to use files in any case, but perhaps store in etcd or another kv store (ah! I see. chicken and egg ;-) )

In the example above, if the data is purely temporary, your approach seems the most appropriate. If it should be long lived then I agree with your point

**Comment by cmgrote** [comment]
In a way it is both: the long-lived version of it will live in the config doc of Egeria itself (so that is already in this location).  I need to create a short-lived subset of that, basically, for startup purposes -- so indeed we could leave this short-lived piece as a temp file.

**Comment by planetf1** [comment]
In that case I'd be inclined to stick with tmp. It's one less piece of persistent data to manage.
