### ISSUE TITLE
Crux migrating to Maven Central

### ISSUE THREAD

**Issue by refset** [odpi/egeria-connector-crux#172]
Hi, a quick heads up that we're looking to migrate Crux over to Maven Central shortly - we've got a couple of non-Clojure modules coming soon, and would generally like to make Crux more accessible/appealing to folks outside of the Clojure community too. We've mirrored our Clojars dependencies onto Central, and have re-released 1.17.1 (currently as 1.17.1-rc1) so that users can migrate without having to upgrade Crux.

Crux PRs here:
* https://github.com/juxt/crux/pull/1543
* https://github.com/juxt/crux/pull/1550

Could you let us know if this will cause you any issues, or whether there's anything we should do/avoid doing? Otherwise, if this works for you, I'm happy to raise a quick PR with the required changes(!)

**Comment by cmgrote** [comment]
This sounds great to me!  I'm just doing some simple tests locally (requires making the changes that need to go into a PR anyway, so no worries I will create a PR here).

**Comment by cmgrote** [comment]
Looks good to me: I'll leave the linked PR as draft until the non-RC versions hit MC, and then will update accordingly.  Are we expecting that relatively imminently?  (We're planning to cut our next Egeria release imminently, so would be nice to have this wrapped in as well 😁 )

**Comment by refset** [comment]
https://twitter.com/juxtpro/status/1410289961820164105 :)
