### ISSUE TITLE
Comments on documentation

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-connector-crux#190]
While viewing the new look and feel for the Crux connector I noticed a number of naming issues that make it hard to connect it with the main Egeria documentation.

On the setup tab:
- [x] server chassis should be OMAG Server Platform
- [x] Configuring the connector - actually this is describing configuring a "Metadata Server" that connects to a cohort.  There are other features that could be enabled - such as the Access Services, audit log destinations, open metadata archives.  Because the crux connector is not positioned as the local repository in a metadata server, it is hard to understand how it fits in the broader ecosystem described in the Admin Guide.
- [x] Start the connector instance - actually this is starting the metadata server

On the explore tab:
- [ ] This is describing using the OMRS API which is not really for general use - It would be helpful in the APIs were put in context - for example if some OMASs were started, some more realistic interaction could be shown .
- [x] It would be OK to show the OMRS interface as a check that the metadata server is running ok - but then link them to the labs or the broader ecosystem.

**Comment by cmgrote** [comment]
> This is describing using the OMRS API which is not really for general use - It would be helpful in the APIs were put in context - for example if some OMASs were started, some more realistic interaction could be shown .

I'd prefer not to introduce any direct reliance on OMASes simply to validate that the repository itself has been configured appropriately -- for me this introduces other moving pieces and potentially changing interfaces that then also need to be kept up-to-date in the guide, etc (vs. the OMRS-level interfaces which have been very stable for a long time now) -- so I'll go with the latter option (OMRS interface as a check, but link to the broader labs).

**Comment by cmgrote** [comment]
Updated documents should now be available (might need to refresh or do a private session browse to make sure the browser is properly pulling back the latest) -- could you have a look and let me know if there are other suggested revisions? 🙏

**Comment by mandy-chessell** [comment]
OK to use OMRS in order to test the connector is working - just needs to be clear this is just a test and not the normal way it is used :)

**Comment by mandy-chessell** [comment]
Just looked at the latest version - looking really nice.  A couple of other thoughts

- the event bus and cohort configuration are not needed to test the repository connector so could make it even simpler by removing those steps.
- it would be good to have a link to the OMAG Server Platform page when it is introduced and similarly for the metadata server like in the TLS section:
    - https://egeria.ai/open-metadata-implementation/admin-services/docs/concepts/omag-server-platform.html
    - https://egeria.ai/open-metadata-implementation/admin-services/docs/concepts/metadata-server.html

**Comment by cmgrote** [comment]
Done -- any others? 😃
