### ISSUE TITLE
Start up diagnostics

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-connector-crux#201]
I picked this up from the PR #200 ... in file CruxOMRSRepositoryConnector.java 

The error handling is using log.error() rather than auditLog.logException().  The reason given is that the auditlog "swallows the stacktrace" which is not true.  Even the console destination outputs the stack trace from the exception

```
        } catch (Exception e) {
            log.error("Unable to start the repository based on the provided configuration.", e);
            // Note: unfortunately the audit log swallows this exception's stack trace, and therefore is insufficient
            // for someone attempting to understand why their configuration did not work -- hence logging an error above
            throw new ConnectorCheckedException(CruxOMRSErrorCode.UNKNOWN_RUNTIME_ERROR.getMessageDefinition(),
                    this.getClass().getName(), methodName, e);
        }
```
The other observation is that many of the audit log messages pass no parameters so it is not possible to see what values were causing the situation that is being logged.  If these messages passed the values relating to the message content then it would be possible to "see" what is causing the problem.

The problem with this code is that the debug logging needs to be turned on just for this repository because it is not creating proper diagnostics through the audit log.

**Comment by mandy-chessell** [comment]
I had a look at the message definitions.  Many do not describe what is happening in the server in the user action and have a user action that documents "no action" rather than a description of what to look out for next in the success case.
Here are some examples...

Message REPOSITORY_SERVICE_STARTING says that the Crux repository is starting a new server instance.  This is confusing because the crux repository is being started up as the local repository inside an OMAG Server instance.  So the description should be clarified to distinguish between the server instance that is part of Crux and the OMAG Server instance.  The user action should describe what to look out for next.

Message REPOSITORY_SERVICE_STARTING_WITH_CONFIG could explain that the configuration defines the persistance store for the repository - so the message itself could be "The Crux repository is starting with a configured persistence store" or something similar and the description could be that this is defined in the configuration properties of the local repository connection.

Message FAILED_RELATIONSHIP_DELETE_CASCADE - is it possible to list the relationships not deleted?  Is it possible to output the exception name and message in the message text? Which logs should the operator look at?

```
public enum CruxOMRSAuditCode implements AuditLogMessageSet {

    REPOSITORY_SERVICE_STARTING("OMRS-CRUX-REPOSITORY-0001",
            OMRSAuditLogRecordSeverity.STARTUP,
            "The Crux repository is starting a new server instance",
            "The local server has started up a new instance of Crux.",
            Constants.NO_ACTION),
    REPOSITORY_SERVICE_STARTING_WITH_CONFIG("OMRS-CRUX-REPOSITORY-0002",
            OMRSAuditLogRecordSeverity.STARTUP,
            "The Crux repository is starting a new instance with the provided configuration",
            "The local server is starting a new instance based on the configuration provided through the configurationProperties.",
            Constants.NO_ACTION),
    REPOSITORY_SERVICE_STARTING_NO_CONFIG("OMRS-CRUX-REPOSITORY-0003",
            OMRSAuditLogRecordSeverity.STARTUP,
            "The Crux repository is starting a new in-memory instance",
            "The local server is starting a new in-memory instance, as no configuration was provided through configurationProperties.",
            Constants.NO_ACTION),
    REPOSITORY_SERVICE_STARTED("OMRS-CRUX-REPOSITORY-0004",
            OMRSAuditLogRecordSeverity.STARTUP,
            "The Crux repository has started a new instance for server {0}, detected Crux version {1}",
            "The local server has completed startup of a new instance.",
            Constants.NO_ACTION),
    REPOSITORY_SERVICE_SHUTDOWN("OMRS-CRUX-REPOSITORY-0005",
            OMRSAuditLogRecordSeverity.SHUTDOWN,
            "The Crux repository has shutdown its instance for server {0}",
            "The local server has requested shut down of a Crux repository instance.",
            Constants.NO_ACTION),
    FAILED_RELATIONSHIP_DELETE_CASCADE("OMRS-CRUX-REPOSITORY-0006",
            OMRSAuditLogRecordSeverity.EXCEPTION,
            "The Crux connector failed to cascade deletions of all relationships for entity {0}",
            "The local server failed to delete all relationships of the entity during the entity's deletion.",
            "Investigate the logs for additional information and cleanup Crux if needed.")
    ;
```

**Comment by cmgrote** [comment]
> The error handling is using log.error() rather than auditLog.logException(). The reason given is that the auditlog "swallows the stacktrace" which is not true. Even the console destination outputs the stack trace from the exception

I see -- good point.  I had at some point assumed that the throw of the ConnectorCheckedException alone would be sufficient (and at some point this didn't produce any stacktrace output in the console), but now that you point out the `auditLog.logException()` suggestion that does make more sense than `log.error()` 🤦   I think I should still throw the ConnectorCheckedException, though as well, to indicate that the repository is in a non-working state (?)

**Comment by cmgrote** [comment]
Thanks for pointing these out -- appreciate if you can have a look at #202 and add any further suggestions?

Have also raised #203 to address other (non-startup) areas where I should be using audit logging.
