### ISSUE TITLE
Translate a query timeout to FunctionNotSupported

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-crux#31]
Detect query timeouts from Crux and translate these into a `FunctionNotSupportedException` for the calling Egeria method (e.g. `findEntitiesByPropertyValue`).

**Comment by cmgrote** [comment]
Or, alternatively, determine if it would make sense to extend the potential exceptions to include a timeout-based exception as a valid outcome from a query (see https://github.com/odpi/egeria/issues/4702)

**Comment by grahamwallis** [comment]
I prefer the latter suggestion - it seems more logical.
