### ISSUE TITLE
Re-order query conditions for very broad queries

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-crux#40]
Consider re-ordering the query conditions in cases where a very broad query will otherwise be executed (i.e. when a user has not specified any type filter, or is searching across `OpenMetadataRoot` or `Referenceable`) -- currently these type conditions are put first, but these two in particular will have little if any effect on limiting, and would probably be better replaced by the property / string against which matching is done (?)

**Comment by grahamwallis** [comment]
Agreed - I find it's best to put the property conditions early in the query (traversal) because they will hit the property indexes. The type name is also an indexed vertex/edge property in the case of the graph repo, but the property clauses in the search are likely to be more selective.
