### ISSUE TITLE
Separate classifications into separate documents?

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-crux#57]
Given that adding a classification to an entity should be possible for reference copies, and that doing so should not increment the version or change the updateTime, should we have a lastClassified time stamp?

This would be helpful to construct the correct history for a reference copy.

**Comment by cmgrote** [comment]
If this shortcut is indeed useful, it can be done internally -- but not change the InstanceAuditHeader (it's a repository-specific optimisation).

**Comment by cmgrote** [comment]
Thinking this through, it initially seemed unlikely that this shortcut would even work in all cases.  For example:

- We receive a reference copy at version 2 which has an `updateTime` of 5
- We later receive a reference copy (still at version 2, `updateTime` of 5) which now has a classification, whose `createTime` is 3

History should show that:

- at time 1 and time 2 we do not know about the entity
- at time 3 and time 4 is now the tricky part: can we say anything about this entity?  (We do not know what version it was at that point in time, or what properties it had -- only that it had a classification...)  So following the rest of the paradigm, it seems that we should still not return this entity -- we did not know anything about its existence at time 3 and 4.
- However, at time 5 we know it is version 2 and that it also has the classification.

So it still seems that the shortcut will work: we insert the validity time (including the classification) based on the `max` of the `updateTime` and any details we have within the classifications.

(Noting here as consideration for the write-up suggested by https://github.com/odpi/egeria/issues/4859

**Comment by grahamwallis** [comment]
Agreed - the repository can only report what it knows/knew at the time. And if it only learns of the entity at T5 then it shouldn't return anything for a query set at a time prior to that. The fact that the classification appears to pre-date this repository's knowledge of the entity doesn't change that - without the reportable entity the classification would just be floating anyway.

**Comment by cmgrote** [comment]
Closing as working as intended -- but will include in write-up of nuances.
